bibliotheque/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('home/', views.get_full_tree, name='home'),
    path('<int:pk>', views.get_full_tree, name='home'),
    path('leaf/delete/<int:pk>', views.deleting_leaf_node, name="delete-leaf-node"),

    path('get_image_list/', views.get_image_list, name='get_image_list'),

    path('bibliotheque/documentitem/data/json/', views.ajax_return_item_object, name='documentitem-ajax-get'),

    path('bibliotheque/requete/text/get/', views.text_get, name='bibliotheque-text-get'),
    path('bibliotheque/requete/text/add/child/', views.add_as_child, name='add-as-child'),
    path('bibliotheque/requete/text/add/child/<int:parent_id>', views.add_as_child, name='add-as-child'),
    path('bibliotheque/requete/text/add/siblings/', views.add_as_sibling, name='add-as-sibling'),
    path('bibliotheque/requete/text/add/siblings/<int:parent_id>', views.add_as_sibling, name='add-as-sibling'),
    path('bibliotheque/requete/text/update/', views.text_update, name='bibliotheque-text-update'),
    path('bibliotheque/requete/text/update/<int:pk>', views.text_update, name='bibliotheque-text-update'),
    path('bibliotheque/requete/text/delete/<int:pk>', views.SectionDeleteModelView.as_view(), name='bibliotheque-section-delete'),

    path('bibliotheque/requete/hierarchy/', views.render_hierarchical_data, name='bibliotheque-hierarchy'),    

    path('bibliotheque/requete/add/section/', views.section_add, name='bibliotheque-section-add'),

    # path('bibliotheque/requete/add/allegation/<int:left_sibling_id>', views.document_allegation_add, name='bibliotheque-allegation-add'),
    # path('bibliotheque/requete/add/section/<int:parent_id>', views.document_item_text_add, name='bibliotheque-section-add-2'),

    path('bibliotheque/requete/add/counterpoint/', views.counterpoint_add, name='bibliotheque-counterpoint-add'),
    path('bibliotheque/requete/add/counterpoint/<int:pk>', views.counterpoint_add, name='bibliotheque-counterpoint-add'),

    path('bibliotheque/requete/add/allegation/', views.allegation_add, name='bibliotheque-allegation-add'),
    path('bibliotheque/requete/add/allegation/<int:pk>', views.allegation_add, name='bibliotheque-allegation-add'),

    
    path('bibliotheque/requete/allegation/<int:pk>', views.get_related, name='bibliotheque-requete-allegation'),

    path('bibliotheque/requete/add/timelinejs/', views.timelinejs_add, name='bibliotheque-timeline-add_'),

    path('bibliotheque/requete/', views.requete, name='hierarchy'),
    path('bibliotheque/rebuttal/<int:pk>', views.rebuttal, name='rebuttal'),

    

    
]

flickr/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('detail/<int:pk>/', views.FlickrPhotoDetailView.as_view(), name='flicker-detail-view'),
    path('update/<int:pk>', views.FlickrPhotoUpdateView.as_view(), name='flicker-update-view'),
    path('update_function/<int:pk>', views.flickr_update_view, name='flicker-update-function-view'),
    path('list/', views.FlickrPhotosListView.as_view(), name='flicker-list-view'),
    path('album/list/<int:album_id>/', views.FlickrAlbumPhotosListView.as_view(), name='flicker-album-view'),

    path('album/create/', views.AlbumCreateView.as_view(), name='album-create-view'),
    # path('album/create2/', views.album_create, name='album-create-view-2'),
    path('album/detail/<int:pk>', views.AlbumDetailView.as_view(), name='album-detail-view'),
    # path('album/list/', views.AlbumListView.as_view(), name='album-list-view'),
    path('album/update/<int:pk>', views.AlbumUpdateView.as_view(), name='album-update-view'),
    path('album/delete/<int:pk>', views.AlbumDeleteView.as_view(), name='album-delete-view'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('bibliotheque.urls')),
    path('photos/', include('photos.urls')),
    path('timelinejs/', include('timelinejs.urls')),
    path("flickr/", include('flickr.urls')),
        # path('user/profile/<pk:int>')

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bibliotheque/models.py
from django.db import models, connection
from django.urls import reverse
import re
# from .forms import DocumentItemForm

# http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/
# https://stackoverflow.com/questions/805393/what-is-the-best-way-to-access-stored-procedures-in-djangos-orm
# Create your models here.


def clean_text(item):
    cleanr = re.compile('<.*?>|&([a-z0-9]+|#[0-9]{1,6}|#x[0-9a-f]{1,6});')
    if item != "" and (type(item) == str):
        cleantext = re.sub(cleanr, '', item)
        return cleantext


class TypeDocument(models.Model):
    desc = models.CharField(max_length=100)

    def __str__(self):
        return self.desc

class DocumentItem(models.Model):
    """
    is_leaf

    get_parent

    get_item_free_of_html

    get_tree

    get_related

    text
    """
    parent = models.IntegerField(null=True)
    lft = models.IntegerField()
    rgt = models.IntegerField()
    item = models.TextField()
    text = models.TextField(null=True, blank=True)
    desc = models.ForeignKey(TypeDocument, on_delete=models.SET_NULL, null=True)
    is_true = models.BooleanField(null=True, default=True)
    # depth = models.SmallIntegerField(null=True, default=None)


    @property
    def width(self):
        return int(self.rgt) - int(self.lft) + 1

    @property
    def get_children(self):
        if self.width == 2:
            return None
        else:
            return DocumentItem.objects.filter(lft__gt=self.lft).filter(lft__lt=self.rgt).order_by('lft')

    @property
    def get_parent(self):
        return self.get_path[-1]

    @property
    def get_item_free_of_html(self):
        cleanr = re.compile('<.*?>|&([a-z0-9]+|#[0-9]{1,6}|#x[0-9a-f]{1,6});')
        if self.item != "" and (type(self.item) == str):
            cleantext = re.sub(cleanr, '', self.item)
            return cleantext

    @property
    def get_tree_old(self):
        element_dict_list = []
        with connection.cursor() as cursor:
            cursor.execute("CALL get_tree_with_depth_raw(" + str(self.id) + ",1)")
            data = cursor.fetchall()

            for row in data:
                data_dict = {"depth": row[6], "document_item_obj": DocumentItem.objects.get(id=row[0])}
                element_dict_list.append(data_dict)

            i = 1
            previous_depth = 0
            for data_dict in element_dict_list:
                if data_dict["depth"] != 0:
                    data_dict["requete_number"] = i
                    i += 1
                this_depth = data_dict["depth"]
                data_dict["previous_depth"] = previous_depth

                if previous_depth - this_depth > 0:
                    data_dict["range"] = range(previous_depth - this_depth)
                else:
                    data_dict["range"] = ""
                previous_depth = this_depth

        return element_dict_list

    @property
    def get_tree(self):
        element_dict_list = []
        with connection.cursor() as cursor:
            cursor.execute("CALL get_tree_with_depth(" + str(self.id) + ")")
            data = cursor.fetchall()

            for row in data:
                data_dict = {"depth": row[3], "document_item_obj": DocumentItem.objects.get(id=row[0])}
                element_dict_list.append(data_dict)

            
            previous_depth = 0
            for data_dict in element_dict_list:

                this_depth = data_dict["depth"]
                data_dict["previous_depth"] = previous_depth
                
                if previous_depth - this_depth == 1:
                    data_dict["range"] = range(1)
                elif previous_depth - this_depth > 1:
                    data_dict["range"] = range(previous_depth - this_depth - 1) 
                else:
                    data_dict["range"] = ""
                previous_depth = this_depth

        return element_dict_list


    @property
    def get_related(self):
        element_dict_list = []
        with connection.cursor() as cursor:
            cursor.execute("CALL get_tree_with_depth_raw(" + str(self.id) + ",3)")
            data = cursor.fetchall()
            for row in data:
                data_dict = {"depth": row[6],
                             "document_item_obj": DocumentItem.objects.get(id=row[0])
                             }
                element_dict_list.append(data_dict)

            i = 1
            previous_depth = 0
            for data_dict in element_dict_list:
                if data_dict["depth"] != 0:
                    data_dict["requete_number"] = i
                    i += 1
                this_depth = data_dict["depth"]
                data_dict["previous_depth"] = previous_depth

                if previous_depth - this_depth > 0:
                    data_dict["range"] = range(previous_depth - this_depth)
                else:
                    data_dict["range"] = ""
                previous_depth = this_depth

        return element_dict_list

    @property
    def get_path(self):
        element_obj_list = []
        with connection.cursor() as cursor:
            cursor.execute("CALL get_single_path(" + str(self.id) + ")")
            data = cursor.fetchall()
            for row in data:
                d = DocumentItem.objects.get(id=row[0])
                element_obj_list.append(d)
        return element_obj_list[1:]

    def assign_as_a_children_to(self, parent_id):
        if self.is_leaf:
            element_obj_list = []
            with connection.cursor() as cursor:
                # add the children
                cursor.execute("CALL add_child_nod(" + str(parent_id) + str(self.item) + ")")
                self.delete()
                cursor.execute("CALL get_tree_with_depth_raw(" + str(parent_id) + ")")
                data = cursor.fetchall()
                for row in data:
                    d = DocumentItem.objects.get(id=row[0])
                    element_obj_list.append(d)
            return element_obj_list
        else:
            return "Element has children, deal with the children first"

    def assign_as_sibling_to(self, sibling_id):
        if self.is_leaf:
            element_obj_list = []
            with connection.cursor() as cursor:
                # add the children
                cursor.execute("CALL add_sibling_nod(" + str(sibling_id) + ", '" + self.item + "')")
                parent_id = self.parent
                self.delete()

                cursor.execute("CALL get_tree_with_depth_raw(" + str(parent_id) + ")")
                data = cursor.fetchall()
                for row in data:
                    d = DocumentItem.objects.get(id=row[0])
                    element_obj_list.append(d)
            return element_obj_list
        else:
            return "Element has children, deal with the children first"

    def __str__(self):
        return str(self.id) + " " + self.get_item_free_of_html

   



class DocumentText(models.Model):
    document_section = models.OneToOneField(DocumentItem, on_delete=models.CASCADE, primary_key=True)
    text = models.TextField()

bibliotheque/forms.py
from django.forms import ModelForm
from .models import DocumentItem, TypeDocument
from django import forms


class DocumentItemForm(ModelForm):

    class Meta:
        model = DocumentItem
        fields = "__all__"

    # def save_as_child(self, commit=True):
    #
    #     instance = super(DocumentItemForm, self).save(commit=False)
    #
    #     lft_itme_qs = DocumentItem.objects.filter(lft__gt=instance.parent_id)
    #     rgt_item_qs = DocumentItem.objects.filter(rgt__gt=instance.parent_id)
    #
    #     for item_lft, item_rgt in zip(lft_itme_qs, rgt_item_qs):
    #         item_lft.lft = item_lft.lft + 2
    #         item_rgt.rgt = item_rgt.rgt + 2
    #         item_lft.save()
    #         item_rgt.rgt.save()
    #
    #     if commit:
    #         instance.save()
    #
    #     return instance
    #
    # def save_as_sibling(self, commit=True):
    #     instance = super(DocumentItemForm, self).save(commit=False)
    #
    #     if commit:
    #         instance.save()
    #
    #     return instance


class RequeteItemModelForm(DocumentItemForm):
    # desc = forms.ModelChoiceField(queryset=TypeDocument.objects.get(id=1),
    #                               widget=forms.HiddenInput())
    class Meta:
        model = DocumentItem
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['parent'].widget = forms.HiddenInput()
        self.fields['lft'].widget = forms.HiddenInput()
        self.fields['rgt'].widget = forms.HiddenInput()
        self.fields['desc'].widget = forms.HiddenInput(attrs={'value': TypeDocument.objects.get(id=1)})
        self.fields['item'].widget = forms.Textarea(attrs={'rows': 4})
        self.fields['text'].widget = forms.HiddenInput(attrs={'value': None})
        self.fields['is_true'].widget = forms.HiddenInput(attrs={'value': False})


class CounterPointModelForm(DocumentItemForm):
    class Meta:
        model = DocumentItem
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['parent'].widget = forms.HiddenInput()
        self.fields['lft'].widget = forms.HiddenInput()
        self.fields['rgt'].widget = forms.HiddenInput()
        self.fields['desc'].widget = forms.HiddenInput(attrs={'value': TypeDocument.objects.get(id=2)})
        self.fields['item'].widget = forms.Textarea(attrs={'rows': 1, 'placeholder': 'Titre de la section'})
        self.fields['item'].label = "Titre de la section"
        self.fields['text'].widget = forms.Textarea(attrs={'rows': 6, 'placeholder': 'Détails'})
        self.fields['item'].label = "Détails de la section"
        self.fields['is_true'].widget = forms.HiddenInput(attrs={'value': None})

bibliotheque/templates/bibliotheque/counterpoint_item_text_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block content %}

<div class="row border rounded px-3 mt-5 pt-3">

    {% for item in parent.get_path %}
        <ul >
            <li>{{ item.item|safe }}</li>
    {% endfor %}
    {% for item in parent.get_path %}
        </ul>
    {% endfor %}
</div>
<form method="post" action="{% url 'bibliotheque-counterpoint-add' parent.id %}">
    {% csrf_token %}

    <div class="row border rounded mt-4">
        {% bootstrap_form item_form %}
        {{ item_form.errors }}
    </div>

    <button type="submit" class="btn btn-primary">Ajouter</button>
</form>

{% endblock %}

bibliotheque/templates/bibliotheque/delete_home2.html
{% extends 'base.html' %}
{% load static %}
<!--<link rel="stylesheet" href="mystyle.css">-->

{% block extrahead %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

{% endblock %}
{% block js %}
    <script src="https://cdn.tiny.cloud/1/3uxow28ssthmenpgxa54gwbtdj7mdpjqzi8sprt26xpv0dcz/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
	<script src="{% static 'bibliotheque/js/inline_editing.js' %}"> </script>
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">

            <div class="col-md-2">
                <div class="row h-100 border">

                </div>
            </div>

            <div class="col">
                <div class="row">
                    <form>
                        {% csrf_token %}
                        {% for data in tree %}
                            {% if data.0 > 1 %}
                                {% if data.4 == 1 %}
                                    <div class="row mt-3 text-black-50">
                                {% else %}
                                    <div class="row mt-3">
                                {% endif %}
                                    {% if data.3 > 0 %}
                                        <div class="row text-container">
                                            <div class="col-sm-1">
                                                {{ data.3 }}.
                                            </div>
                                            <div class="col inline_textarea" id="{{ data.0 }}">
                                                {{ data.1|safe }}
                                            </div>
                                        </div>
                                        <div class="row option-menu justify-content-end">
                                            <div class="col-md-2 sm-12">
                                                Edit text
                                            </div>
                                            <div class="col-md-2 sm-12">
                                                delete leaf
                                            </div>
                                            <div class="col-md-2 sm-12">
                                                add children
                                            </div>
                                            <div class="col-md-1 sm-12">
                                                <span class="material-symbols-outlined">
                                                    arrow_upward
                                                </span>
                                            </div>
                                            <div class="col-md-1 sm-12">
                                                <span class="material-symbols-outlined">
                                                    arrow_downward
                                                </span>
                                            </div>
                                        </div>
                                    {% else %}
                                        <div class="col"><h3>{{ data.1|capfirst }}</h3></div>
                                    {% endif %}
                                </div>
                            {% endif %}
                        {% endfor %}
                    </form>
                </div>

            </div>

            <div class="col-md-1">

            </div>
        </div>
        <div class="row">
            {% include 'photos/timeline_js.html' %}
        </div>
    </div>
    <img src="https://live.staticflickr.com/65535/52393299665_82ba29620d_h.jpg" alt="HTML tutorial" style="width:42px;height:42px;">

{% endblock %}

bibliotheque/templates/bibliotheque/documentitem_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <div class="row mb-5">
        Êtes vous certain de vouloir deleter l'élément {{object.desc.desc}} ?
    </div>
    <dic class="row">
        {{ object.item }}
    </dic>
    <dic class="row mb-5">
        {{ form }}
    </dic>
    <dic class="row">
        <div class="col-sm-2">
            <a href="{% url 'home' %}" class="btn btn-primary"> Cancel </a>
        </div>
        <div class="col-sm-2">
            <div class="btn btn-danger" type="submit" value="Confirm"> Delete </div>
        </div>
    </dic>

</form>

{% endblock %}

bibliotheque/templates/bibliotheque/form_modal_allegation copy.html
{% load bootstrap5 %}

<!-- Modal -->

<div class="modal fade" id="addAllegationModal" tabindex="-1" aria-labelledby="addAllegationModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="addAllegationModalLabel"> Insert Allegation as sibling </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Anuler"></button>
            </div>

            <form method="post" action="{% url 'bibliotheque-allegation-add' %}">

                {% csrf_token %}
<!--                <input type="hidden" name="parent_id" value="#">-->
                <div class="modal-body">
                    <div class="row">
                        {% for item in sibling.get_path %}
                            {{item}}
                        {% endfor %}
                    </div>
                     <div class="row border rounded mt-4">
                        <input type="hidden" name="parent" value="#" id="id_parent">
                        <input type="hidden" name="lft" value="#" id="id_lft">
                        <input type="hidden" name="rgt" value="#" id="id_rgt">

                        <div class="mb-3"><label class="form-label" for="id_item">Allégation</label>
                            <textarea name="item" cols="40" rows="4" class="form-control" placeholder="Allégation" title="" required id="id_item"></textarea>
                        </div>

                        <div class="mb-3">
                            <label class="form-label" for="id_is_true">Is true</label>
                            <select name="is_true" class="form-select" title="" id="id_is_true">
                                <option value="true" selected>Yes</option>
                                <option value="false">No</option>
                            </select>
                        </div>

                    </div>


                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Soumettre</button>
                </div>

            </form>

        </div>
    </div>
</div>

bibliotheque/templates/bibliotheque/form_modal_allegation.html
{% load bootstrap5 %}

<!-- Modal -->

<div class="modal fade" id="addChild" tabindex="-1" aria-labelledby="addChildLabelle" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="addChildLabelle"> Inséré cotre-point comme enfant </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Anuler"></button>
            </div>

            <form method="post" action="{% url 'add-as-child' %}">
                {% csrf_token %}

                <input type="hidden" name="parent_id" value="#">
                <input type="hidden" name="action_type" value="#">

                <div class="modal-body">
                    <div class="row">
                        <div class="statement-to-comment"></div>
                    </div>
                    
                    <div class="row">
                        <div class="inline_textarea_explanation">
                            
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Soumettre</button>
                </div>

            </form>

        </div>
    </div>
</div>

bibliotheque/templates/bibliotheque/form_modal_edit_text.html
<!-- Modal -->
<div class="modal fade" id="editFalseAllegationModal" tabindex="-1" aria-labelledby="editFalseAllegationModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editFalseAllegationModalLabel">Modifier le Text</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Anuler"></button>
            </div>
<!--            <form method="post" action="{% url 'bibliotheque-text-update' %}">-->
            <form method="post" action="{% url 'add-as-child' %}" id="main_form">
                {% csrf_token %}
                
                <input type="hidden" name="parent_id" value="#">

                <div class="modal-body">
                <!--     contenu       -->
                        <div class="row mt-4">
                            <div class="form-group inline_textarea_explanation"></div>
                        </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary close-edit-text-modal" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Soumettre</button>
                    <a href="#" class="btn btn-danger">Delete</a>
                </div>

            </form>

        </div>
    </div>
</div>

bibliotheque/templates/bibliotheque/form_modal_explication_old.html
<!-- Modal -->
<div class="modal fade" id="addExplainationeModal" tabindex="-1" aria-labelledby="addExplainationeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addExplainationeModalLabel">Insert as a child</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Anuler"></button>
            </div>
            <form method="post" action="{% url 'bibliotheque-section-add' %}">
                {% csrf_token %}
                <input type="hidden" name="parent_id" value="#">

                <div class="modal-body">

                    <div class="row statement-to-comment"></div>

                    <div class="row">

                        <label for="basic-url" class="form-label">Titre du commentaire</label>
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Comment's title" aria-label="Comment's title" name="explanation-title">
                        </div>

                    </div>

                    <div class="row mt-4">
                        <div class="form-group">
                            <textarea class="inline_textarea_explanation" name="explanation"></textarea>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Soumettre</button>
                </div>
            </form>

        </div>
    </div>
</div>

bibliotheque/templates/bibliotheque/form_modal_timeline.html
<!-- Modal -->
<div class="modal fade" id="addTimelineModal" tabindex="-1" aria-labelledby="addTimelineModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="addTimelineModalLabel">Insert Timeline as a child</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <!--form-->
            <form method="post" action="{% url 'bibliotheque-timeline-add_' %}" name="formAddTimelineModal">
            <!--  form          -->
                {% csrf_token %}
                <div class="modal-body">

                    <div class="row">
                        <input type="hidden" name="timeline_related_item" value="#">

                        <div id="timeline-related-item"></div>

                    </div>

                    <div class="row mt-4">
                        <div class="form-group">
                            <select class="form-control" name="timeline_id" id="select-timeline">
                                {% for timeline in timelines %}
                                    <option value="{{ timeline.id }}">
                                        {{ timeline.title.text.headline }}
                                    </option>

                                {%endfor%}
                            </select>
                        </div>
                    </div>

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary close-edit-text-modal" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Soumettre</button>
                </div>

            </form>



        </div>
    </div>
</div>

bibliotheque/templates/bibliotheque/rebuttal_reveal.html
{% extends 'base.html' %}
{% load static %}
<!--<link rel="stylesheet" href="mystyle.css">-->

{% block extrahead %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
<link title="timeline-styles" rel="stylesheet" href="https://cdn.knightlab.com/libs/timeline3/latest/css/timeline.css">
<link rel="stylesheet" href="{% static 'bibliotheque/css/rebuttal_reveal.css' %}" />
{% endblock %}

{% block js %}
<!--<script src="https://cdn.tiny.cloud/1/3uxow28ssthmenpgxa54gwbtdj7mdpjqzi8sprt26xpv0dcz/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>-->
<!--<script src="https://cdn.knightlab.com/libs/timeline3/latest/js/timeline.js"></script>-->
<!--<script src="{% static 'bibliotheque/js/hoover_menu.js' %}"> </script>-->
<!--<script src="{% static 'bibliotheque/js/timeline.js' %}"> </script>-->
<script src="{% static 'bibliotheque/js/rebuttal_scroll.js' %}"> </script>
{% endblock %}

{% block content %}
    <div class="rebuttal-body">

        <section>
            <div class="container reveal">
                <h2> {{allegation.item|safe}}</h2>
            </div>
        </section>

        {% for item in allegation.get_related %}
            {% if item.document_item_obj.desc.id != 3 and item.document_item_obj.id != allegation.id %}

                <section>
                    <div class="container reveal">
                        <h2> {{item.document_item_obj.item|safe}}</h2>
                    </div>
                </section>

            {% endif %}
        {%endfor%}
    </div>




{% endblock %}