flickr/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('detail/<int:pk>/', views.FlickrPhotoDetailView.as_view(), name='flicker-detail-view'),
    path('update/<int:pk>', views.FlickrPhotoUpdateView.as_view(), name='flicker-update-view'),
    path('update_function/<int:pk>', views.flickr_update_view, name='flicker-update-function-view'),
    path('list/', views.FlickrPhotosListView.as_view(), name='flicker-list-view'),
    path('album/list/<int:album_id>/', views.FlickrAlbumPhotosListView.as_view(), name='flicker-album-view'),

    path('album/create/', views.AlbumCreateView.as_view(), name='album-create-view'),
    # path('album/create2/', views.album_create, name='album-create-view-2'),
    path('album/detail/<int:pk>', views.AlbumDetailView.as_view(), name='album-detail-view'),
    # path('album/list/', views.AlbumListView.as_view(), name='album-list-view'),
    path('album/update/<int:pk>', views.AlbumUpdateView.as_view(), name='album-update-view'),
    path('album/delete/<int:pk>', views.AlbumDeleteView.as_view(), name='album-delete-view'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('bibliotheque.urls')),
    path('photos/', include('photos.urls')),
    path('timelinejs/', include('timelinejs.urls')),
    path("flickr/", include('flickr.urls')),
        # path('user/profile/<pk:int>')

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flickr/models.py
from django.db import models
# Create your models here.

class Flickr(models.Model):
    date_taken = models.CharField(max_length=30)
    date_taken_obj = models.DateTimeField()
    credit = models.CharField(max_length=200)
    title = models.CharField(max_length=500)
    desc = models.TextField()
    link_to_original_photo = models.URLField()
    link_to_photo_thumbnail = models.URLField()

    class Meta:
        ordering = ['date_taken_obj',]


    def __str__(self):
        return self.date_taken +" - " + self.title
    
    @property
    def date_dict(self):
        return {'year': self.date_taken_obj.year,
                'month': self.date_taken_obj.month,
                'day': self.date_taken_obj.day,
                'hour': self.date_taken_obj.hour,
                'minute': self.date_taken_obj.minute,
                'second': self.date_taken_obj.second
                }


class Album(models.Model):
    name = models.CharField(max_length=250, unique=True)
    desc = models.TextField(blank=True, null=True)
    photos = models.ManyToManyField(Flickr, blank=True)

    def __str__(self):
        return self.name



# class TimeLineJSFlickr(models.Model):

flickr/forms.py
from django.forms import ModelForm
from django import forms

from .models import Flickr, Album


class FlickrModelForm(ModelForm):
    class Meta:
        model = Flickr
        fields = ['title', 'desc']

class FlickrAlbumModelForm(ModelForm):

    class Meta:
        model = Album
        fields = '__all__'

    photos = forms.ModelMultipleChoiceField(
        queryset=Flickr.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

class FlickrAlbumNoPhotosModelForm(ModelForm):

    class Meta:
        model = Album
        exclude = ('photos',)

flickr/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView

from .models import Flickr, Album
from .forms import FlickrModelForm, FlickrAlbumModelForm, FlickrAlbumNoPhotosModelForm

# Create your views here.


class FlickrPhotoDetailView(DetailView):
    model = Flickr
    context_object_name = "photo"
    queryset = Flickr.objects.all()
    # template_name = 'flickr/photo_detail.html'


class FlickrPhotoUpdateView(UpdateView):
    model = Flickr
    context_object_name = "photo"
    # template_name = 'flickr/flickr_form.html'
    fields = '__all__'


def flickr_update_view(request, pk):
    f = Flickr.objects.get(id=pk)
    if request.method == "POST":
        form = FlickrModelForm(request.POST, instance=f)
        if form.is_valid():
            form.save()
            return redirect('flicker-list-view')
    else:
        form = FlickrModelForm(instance=f)

    return render(request, 'flickr/flickr_form.html', {'form': form, 'pk': pk, 'photo': f})


class FlickrPhotoDeleteView(DeleteView):
    model = Flickr
    success_url = reverse_lazy('flicker-list-view')


class FlickrPhotosListView(ListView):
    queryset = Flickr.objects.order_by('date_taken_obj')
    context_object_name = "photo_list"
    template_name = 'flickr/photo_list.html'


class FlickrAlbumPhotosListView(ListView):
    template_name = 'flickr/photo_by_album.html'

    def get_queryset(self):
        return Flickr.objects.filter(album__id=self.kwargs['album_id'])


def album_create(request):
    if request.method == "POST":
        # request.POST._mutable = True
        form = FlickrAlbumModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('album-list-view')
        else:
            selected_photos = request.POST.get("photos")
            photos = Flickr.objects.all().order_by('date_taken_obj')
            form = FlickrAlbumNoPhotosModelForm(request.POST)
            context={'selected_photos': selected_photos,
                     'photos': photos,
                     'form': form
                     }
            return render(request, 'flickr/album_create_form.html', context)
    else:
        photos = Flickr.objects.all().order_by('date_taken_obj')
        form = FlickrAlbumNoPhotosModelForm()
        context={'form': form, 'photos': photos}
        return render(request, 'flickr/album_create_form.html', context)


class AlbumCreateView(CreateView):
    model = Album
    form_class = FlickrAlbumModelForm
    success_url = 'album-list-view'


class AlbumDetailView(DetailView):
    model = Album
    template_name_suffix = '_details'


class AlbumListView(ListView):
    model = Album
    context_object_name = 'album_list'


class AlbumUpdateView(UpdateView):
    model = Album
    fields = '__all__'
    template_name_suffix = '_update_form'
    success_url = 'album-list-view'


class AlbumDeleteView(DeleteView):
    model = Album
    success_url = reverse_lazy('album-list-view')

def json_flickr_data(request):
    context={}
    return redirect(request, "", context)

flickr/templates/flickr/album_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block js %}

{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="row">
                <h1>Delete</h1>
            </div>


                <form method="post">
                    <div class="row">
                        {% csrf_token %}
                        <p>Delete {{object}}</p>
                        {% bootstrap_form form %}
                        <input type="submit" value="Confirm" class="btn btn-danger">
                    </div>
                </form>


        </div>
    </div>
{% endblock %}

flickr/templates/flickr/album_create_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block extrahead %}

{% endblock %}


{% block js %}

{% endblock %}

{% block content %}
<!--    <div class="container fixed-top" style="height:100px; background-color:red;">-->

<!--    </div>-->
    <div class="container" style="height:100px">
        <div class="row mt-2">
            <div class="row">
                <h1>Photos Album Create / Update</h1>
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="row mt-5 mb-3">
                    {% bootstrap_form form %}
                </div>
                <div class="row mb-3">
                    <label class="form-label">Photos</label>
                        <div id="id_photos">
                            {% for photo in photos %}

                                    <div class="card mt-5" style="width: 23rem;">
                                        <img src="{{photo.link_to_photo_thumbnail}}" class="card-img-top">
                                        <div class="card-header">
                                            <div class="row">
                                                {{photo.title}}
                                            </div>
                                            <div class="row">
                                                <button type="button" class="btn btn-success btn-sm"> Edit picture details </button>
                                            </div>
                                        </div>
                                        <div class="card-body">
                                            <p class="card-text text-primary"> date : {{photo.date_taken}}</p>
                                            <p class="card-text text-muted">{{photo.desc}}</p>
                                            <div class="card-header">
                                                Appears in:
                                            </div>
                                            {% if photo.album_set.all %}
                                                <ul class="list-group list-group-flush">
                                                {% for album in photo.album_set.all %}
                                                    <li class="list-group-item">
                                                        {{ album }}
                                                    </li>
                                                {% endfor %}
                                                </ul>
                                            {% endif %}
                                        </div>
                                        <div class="card-footer">
                                            <div>
                                                <a href="{{photo.link_to_original_photo}}" class="btn btn-primary">View</a>
                                            </div>
                                            <label for="id_photos_{{ forloop.counter0 }}">
                                                <input id="id_photos_{{ forloop.counter0 }}" type="checkbox" name="photos" value="{{photo.id}}" > Select
                                            </label>
                                        </div>
                                    </div>

                            {% endfor %}
                        </div>
                </div>
                <div class="button-group" role="group">
                    <input type="submit" class="btn btn-primary" value="Save">
<!--                    <input type="submit" class="btn btn-primary" value="Update">-->
                    <a href="{% url 'album-list-view' %}" class="btn btn-danger"> Cancel </a>

                </div>
            </form>

        </div>
    </div>
{% endblock %}

flickr/templates/flickr/album_details.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block js %}

{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="row">
                <h1>Album Details</h1>
            </div>
            
            <div class="row">
                <h4>{{album.name}}</h4>
            </div>
            <div class="row">
                <p>{{album.desc}}</p>
            </div>
            <div class="row">
                {% for photo in album.photos.all %}
                    <div class="card mt-5" style="width: 23rem;">
                        <img src="{{photo.link_to_photo_thumbnail}}" class="card-img-top">
                        <div class="card-header">
                            <div class="row">
                                {{photo.title}}
                            </div>
                            <div class="row">
                                <button type="button" class="btn btn-success btn-sm"> Edit picture details </button>
                            </div>
                        </div>
                        <div class="card-body">
                            <p class="card-text text-primary"> date : {{photo.date_taken}}</p>
                            <p class="card-text text-muted">{{photo.desc}}</p>
                            <div class="card-header">
                                Appears in:
                            </div>
                            {% if photo.album_set.all %}
                                <ul class="list-group list-group-flush">
                                {% for album in photo.album_set.all %}
                                    <li class="list-group-item">
                                        {{ album }}
                                    </li>
                                {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                        <div class="card-footer">
                            <div>
                                <a href="{{photo.link_to_original_photo}}" class="btn btn-primary">View</a>
                            </div>
                            <label for="id_photos_{{ forloop.counter0 }}">
                                <input id="id_photos_{{ forloop.counter0 }}" type="checkbox" name="photos" value="{{photo.id}}" > Select
                            </label>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

flickr/templates/flickr/album_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block js %}

{% endblock %}

{% block content %}
<!--    <div class="container fixed-top" style="height:100px; background-color:red;">-->

<!--    </div>-->
    <div class="container" style="height:100px">
        <div class="row mt-2">
            <div class="row">
                <h1>Photos Album Create / Update</h1>
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="row mt-5 mb-3">
                    {% bootstrap_form form %}
                </div>
                <div class="button-group" role="group">
                    <input type="submit" class="btn btn-primary" value="Save">
<!--                    <input type="submit" class="btn btn-primary" value="Update">-->
                    <a href="{% url 'album-list-view' %}" class="btn btn-danger"> Cancel </a>

                </div>
            </form>

        </div>
    </div>
{% endblock %}

flickr/templates/flickr/album_list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block js %}

{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="row">
                <h1>Album list -</h1>
            </div>
            
            <div class="row">
                {% for album in album_list %}
                    <div class="card mt-3 mx-2" style="width: 18rem;">

                        <div class="card-body">
                            <h5 class="card-title">{{album.name}}</h5>

                            <p class="card-text">{{album.desc}}</p>
                            <p class="card-text">{{photo.link_to_original_photo}}</p>
                            <a href="{% url 'album-update-view' album.id %}" class="btn btn-primary">Edit</a>
                            <a href="{% url 'album-detail-view' album.id %}" class="btn btn-success">View</a>
                            <a href="{% url 'album-delete-view' album.id %}" class="btn btn-danger">Delete</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

flickr/templates/flickr/album_update_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block js %}

{% endblock %}

{% block content %}
<!--    <div class="container fixed-top" style="height:100px; background-color:red;">-->

<!--    </div>-->
    <div class="container" style="height:100px">
        <div class="row mt-2">
            <div class="row">
                <h1>Photos Album Create / Update</h1>
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="row mt-5">
                    {% bootstrap_form form %}
                </div>
                <div class="button-group" role="group">
<!--                    <input type="submit" class="btn btn-primary" value="Save">-->
                    <input type="submit" class="btn btn-primary" value="Update">
                    <a href="{% url 'album-list-view' %}" class="btn btn-danger"> Cancel </a>

                </div>
            </form>

        </div>
    </div>
{% endblock %}

flickr/templates/flickr/flickr_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block js %}

{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="row">
                <h1>Delete</h1>
            </div>

            <div class="row">
                <form method="post" action="{% url 'flicker-update-view' photo.id %}">
                    {% csrf_token %}
                    {{form.as_table}}
                    <div class="btn btn-primary"> Update </div>
                </form>

            </div>
        </div>
    </div>
{% endblock %}

flickr/templates/flickr/flickr_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block js %}

{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="row">
                <h1>Create / Update</h1>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <img src="{{photo.link_to_photo_thumbnail}}" alt="..." class="img-thumbnail">
                </div>
            </div>
            <div class="row">
                <form method="post" action="{% url 'flicker-update-function-view' pk %}">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button class="btn btn-primary" type="submit"> Update </button>
                    <button class="btn btn-primary"> Cancel </button>
                </form>

            </div>
        </div>
    </div>
{% endblock %}

flickr/templates/flickr/photo_by_album.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block js %}

{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="row">
                <h1>Album</h1>
            </div>
            
            <div class="row">

            </div>
        </div>
    </div>
{% endblock %}

flickr/templates/flickr/photo_detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block js %}

{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="row">
                <h1>Timeline detail</h1>
            </div>
            
            <div class="row">

            </div>
        </div>
    </div>
{% endblock %}

flickr/templates/flickr/photo_list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block js %}

{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="row">
                <h1>Photos list</h1>
            </div>
            
            <div class="row">
                {% for photo in photo_list%}
                    <div class="card mt-3 mx-4" style="width: 18rem;">
                        <img class="card-img-top" src="#" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">{{photo.title}}</h5>
                            <p>{{photo.date_taken}}</p>
                            <p class="card-text">{{photo.desc}}</p>
                            <p class="card-text">{{photo.link_to_original_photo}}</p>
<!--                            <a href="{% url 'flicker-update-view' photo.pk %}" class="btn btn-primary">Update</a>-->
                            <a href="{% url 'flicker-update-function-view' photo.id %}" class="btn btn-primary">Update</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}